--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Teunboeke/changelogg
build-by-default: true
branches:
- master
projects: [changelogg]
path ""
icon: 1_gJj1jwKp47hdI9W4eR7FIg.png
...
