name: changelogg
main: Teunboeke/changelogg/main
api: 3.0.0
version: 2.0
depend: []
author: Teunboeke
description:
permisions: 
changelogg:
 description: "permissions to read changelogg"
 default: true
