name: changelogg
main: Teunboeke/changelogg/main
api: [5.6, 7.0]
version: 2.0
author: Teunboeke
description: "a pocketmine plugin that let players know updates"
changelogg:
 
 permisions:
 command.read.changelogg
 default: true
